repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: check-ast
      - id: end-of-file-fixer
  - repo: 'https://github.com/psf/black'
    rev: 19.10b0
    hooks:
      - id: black
        args: [--skip-string-normalization, --line-length=79]
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.2
    hooks:
      - id: flake8
        args: [--max-line-lengt=95, --extend-ignore=E203]
default_language_version:
    python: python3.10
    